apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot
  name: springboot
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - image: docker.io/pratheebapc/springboot-images-new
        imagePullPolicy: IfNotPresent
        name: springboot
        resources:
          requests:
            memory: "64Mi"
            cpu: "150m"
          limits:
            memory: "128Mi"
            cpu: "300m"
